### ISSUE TITLE
调度模块与Kether import

### ISSUE THREAD

**Issue by inrhor** [Lanscarlos/Vulpecula#1]
```
[01:08:28] [Server thread/WARN]: [Vulpecula] Unexpected exception while running the kether script.
[01:08:28] [Server thread/WARN]: [Vulpecula] java.lang.IllegalStateException: unavailable
```

当语句涉及import，则会引起此错误。在`/vulpecula reload`后正常运行，或者设置目标插件先于Vulpecula加载（插件加载顺序）才不会引起此错误。

**Comment by Lanscarlos** [comment]
那个...能给一下出现报错时的具体配置文件吗？

**Comment by inrhor** [comment]
```yaml
on-player-join:
  listen: 'org.bukkit.event.player.PlayerJoinEvent'
  post-handle: |-
      import invero
      menu open welcome
```
